services:
  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: innoinvest
      POSTGRES_USER: innoinvest
      POSTGRES_PASSWORD: innoinvest
    ports:
      - "5434:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./db/migrations:/docker-entrypoint-initdb.d:ro

volumes:
  db_data:
